//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.Entity;

namespace SimpleWebApp.Models
{
    public interface IMvcWebProjectEntities2
    {
        DbSet<Person> People { get; set; }
        DbSet<PersonStatu> PersonStatus { get; set; }
    }
}