//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonsStatu
    {
        public PersonsStatu()
        {
            this.People = new HashSet<Person>();
        }
    
        public int Id { get; set; }
        public string StatusName { get; set; }
    
        public virtual ICollection<Person> People { get; set; }
    }
}
